### PR TITLE
Add new orders Option

### LINKED ISSUE #116: Cucumber 4.2.1 fails  due to the new "order" option, but 4.1.0 works
Hey, just installed the https://github.com/webdriverio/cucumber-boilerplate and it fails due to error

<details>
<summary>Expand stack trace</summary>

```
Type    at orderTestCases (/home/circleci/repo/node_modules/cucumber/src/cli/helpers.js:74:28)
    at Object.<anonymous> (/home/circleci/repo/node_modules/cucumber/src/cli/helpers.js:41:3)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/circleci/repo/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/circleci/repo/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/circleci/repo/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/circleci/repo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/circleci/repo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/circleci/repo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/circleci/repo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/circleci/repo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
</details>

If you check [cucumber changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#420-2018-04-03) for version 4.2.0 there is a new option `order` now required to pass into [getTestCasesFromFilesystem](https://github.com/webdriverio/wdio-cucumber-framework/blob/master/lib/adapter.js#L76) which webdriver adapter not yet supports.

I had to lock down version to 4.1.0 to make tests work.

Looks like a small fix, thanks in advance!

### PR DESCRIPTION
**Pull request by swissmanu**
`cucumber@4.2.0` introduced a new `order` option. This change adds `order` to `DEFAULT_OPS` and should fix #116.

### CODE REVIEW

**Comment by BorisOsipov** [comment]
reran

**Comment by christian-bromann** [comment]
I feel like someone already posted this issue:
```

     TypeError: Cannot read property 'split' of undefined
      at orderTestCases (node_modules/cucumber/src/cli/helpers.js:74:22)
      at Object.<anonymous> (node_modules/cucumber/src/cli/helpers.js:41:3)
      at next (native)
      at undefined.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by Xotabu4** [comment]
Thanks for fix!

**Comment by BorisOsipov** [comment]
I've fixed tests.
@swissmanu thank you for PR.

**Comment by swissmanu** [comment]
thx for revising my PR @BorisOsipov !

**Comment by Xotabu4** [comment]
Hi, can we publish minor version bump to npm? I would love to remove my overrides in package-lock.json, and peoples are trying to apply my fix also.

**Comment by christian-bromann** [comment]
I can take care of this

**Comment by christian-bromann** [comment]
Released as 2.1.0

**Pull request merged**
