### PR TITLE
Upgrade to latest cucumber 3.2.1

### PR DESCRIPTION
**Pull request by devth**
Not sure what all needs to happen to support upgrading but thought I'd start the conversation here.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@devth as you can see in the tests, some of the integrations are failing. There are some breaking changes that need to get adapted here first.

**Comment by devth** [comment]
Yep, I see. Any plans to make them? Should I dive in and try or is it a pretty involved task?

**Comment by christian-bromann** [comment]
> Any plans to make them?

Not my highes priority right now

> Should I dive in and try or is it a pretty involved task?

No, feel free to look into it

**Comment by devth** [comment]
Ok will do! (Reason is I want to use `BeforeAll` then realized wdio was using an older version before `BeforeAll` was introduced.)

**Comment by devth** [comment]
npm 5.x generates a `package-lock.json` to lock down dep versions. Want me to add it as part of this PR?

**Comment by christian-bromann** [comment]
> Want me to add it as part of this PR?

Sure

**Comment by devth** [comment]
This might be as far as I get for now. Confused by test errors and it looks like it'll require a lot of changes.

**Comment by ashmind** [comment]
I did some research on this one — for 4.0.0, but I think it's the same issues.

The test fail with `{stringInDoubleQuotes}` is easy to fix — can be replaced with `{string}`.

However, there is also a change in how hooks are implemented. My understanding is that the hooks from before supported async handlers, but latest Cucumber uses `EventEmitter` without `async` support. I considered using `Before`/`After` instead, however that's only for scenarios. `BeforeStep` is considered (cucumber/cucumber-js#997), but not implemented yet.

I'm hardly an expert on this, but feels like this is blocked until there are some changes in Cucumber.

**Comment by christian-bromann** [comment]
Fixed by #104

**Pull request closed without merging**
