### PR TITLE
Update to cucumber 4.1.0.0

### PR DESCRIPTION
**Pull request by mhoyer**
This is a first attempt to support cucumber v4. I am still testing with our local wdio-cucumber test cases. Feel free to try it on yours as well.

### CODE REVIEW

**Comment by christian-bromann** [comment]
Awesome work @mhoyer , thanks so much ❤️

**Comment by mhoyer** [comment]
@christian-bromann, you're welcome. But again, test it carefully with existing cucumber projects and please review my changes. Maybe I've overlooked something.

**Comment by christian-bromann** [comment]
Changes look good. The test suite is pretty extensive so I am confident that this is good to go and can be released. I will bump the major version so it won't break anyones test unless someone intentionally updates the adapter.

**Comment by mhoyer** [comment]
Perfect. But also `README.md` needs a little massage I guess. 😏

**Comment by christian-bromann** [comment]
Good point. I will take care of this.

**Comment by christian-bromann** [comment]
Released as v2.0.0

**Pull request merged**
