### PR TITLE
Fix events order.

### PR DESCRIPTION
**Pull request by imdmitrykravchenko**
Fixes https://github.com/webdriverio/wdio-cucumber-framework/issues/142

### CODE REVIEW

**Comment by wswebcreation** [comment]
Hi @imdmitrykravchenko 

I've already checked it and it fixes the order, tnx for it!. 

I do have a question about it, this PR doesn't fix the scenario name and step name when a scenario outline is used. It that on purpose, because that is also handled in issue https://github.com/webdriverio/wdio-cucumber-framework/issues/142

Again, thanks for this PR

**Comment by wswebcreation** [comment]
Tnx

I'll check it tonight/this weekend. Will let you know.

Tnx for picking this up!

**Comment by christian-bromann** [comment]
> As far as I can see this can be merged and released.

Got it 👍

**Comment by wswebcreation** [comment]
@christian-bromann 

I thought you had weekend ;-). Tnx for the quick response

**Comment by BorisOsipov** [comment]
I've also checked it on my project. It works like a charm. Thanks @imdmitrykravchenko!

**Pull request merged**
