### PR TITLE
Expose tags in events

### PR DESCRIPTION
**Pull request by cnatis**
Fixes part of https://github.com/webdriverio/wdio-cucumber-framework/issues/74

Exposes the applicable tags in the events that are emitted to be handled by reporters

### CODE REVIEW

**Comment by cnatis** [comment]
I updated the unit tests, but couldn't actually run them locally :/

```babel-node ./node_modules/.bin/isparta cover --include 'lib/*.js' _mocha -- 'test/!(adapter.spec).js'

.js' was unexpected at this time.```

**Comment by cnatis** [comment]
Oops, have to fix the test, slight issue

**Comment by cnatis** [comment]
I updated the tests, the ones I changed are still passing, but it seems some of the existing ones are throwing errors :(

**Comment by cnatis** [comment]
Seems to have been a fluke, its passing now :) still a bit concerned about why the tests don't run on my local machine though, ill get more details and open an issue

**Comment by christian-bromann** [comment]
@cnatis I appreciate it! I will merge and publish this as soon as I have a free minute

**Comment by christian-bromann** [comment]
wdio-cucumber-framework 1.0.2 published 🎉

**Pull request merged**
